### ISSUE TITLE
Lägg till ett Authorize-attribut på ProductsController

### ISSUE THREAD

**Issue by TobiasAhnoff** [Omegapoint/rest-sec-net#4]
Authorize-attribut kan läggas in i Controller också, jag tycker det är tydligt och bra att även om vi också har authfiltret, bra att snabbt kunna se på en controller att inga anonyma anrop tillåts, i fall man skulle ha missat att får med filtret i startup.cs...

**Comment by altenstedt** [comment]
Adding an authorize attribute to all controllers also makes the purpose of the `RequireAuthenticatedUser` policy a little less clear, IMHO.  If we have Authorize on all controllers, then we do not need that policy.

**Comment by TobiasAhnoff** [comment]
We will show and talk (briefly) about MVC Authorization policies in demo 1 (no code change needed)
